"""PatchProposal schema — a unified diff generated by the Surgeon agent."""

from datetime import datetime, timezone

from pydantic import BaseModel, Field


class PatchProposal(BaseModel):
    id: str
    finding_id: str
    diff: str
    explanation: str
    model_used: str
    attempt: int = 1
    prior_concerns: list[str] | None = None
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
